version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=secret
      - PGUSER=postgres
      - PGPASSWORD=achref
      - PGHOST=db
      - PGDATABASE=iset
      - PGPORT=5432
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: iset
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: achref
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
